puppetlabs/courseware-lvm

Quest_Guide/afterword.md
Quest_Guide/index.md
Quest_Guide/quests/mysql.md
Quest_Guide/quests/ntp.md
Quest_Guide/quests/power_of_puppet.md
Quest_Guide/quests/resources.md

Just some small issues I noticed while going through the Learning VM.

Grammar and syntax

---

Quest_Guide/quests/power_of_puppet.md

Wordsmith as needed please, I'm not sure this is the best way to explain this.

Further clarity about modules for offline

---

Quest_Guide/css/main.css

Refactored and reorganized remaining css except for the @media print section.  Syntax.css should not be needed anymore; I will remove that and references to it in another pr.

Refactor css

---

Quest_Guide/quests/power_of_puppet.md

Initial version of the new Power of Puppet quest.

New power quest

---

Quest_Guide/quests/variables_and_parameters.md
Rakefile
quest_tool/.testing/spec/localhost/conditional_statements_spec.rb
quest_tool/.testing/spec/localhost/manifests_and_classes_spec.rb
quest_tool/.testing/spec/localhost/modules_spec.rb
quest_tool/.testing/spec/localhost/mysql_spec.rb
quest_tool/.testing/spec/localhost/ntp_spec.rb
quest_tool/.testing/spec/localhost/resource_ordering_spec.rb
quest_tool/.testing/spec/localhost/resources_spec.rb
quest_tool/.testing/spec/localhost/variables_and_parameters_spec.rb
quest_tool/.testing/spec/localhost/welcome_spec.rb
quest_tool/.testing/spec/spec_helper.rb

Update spec format to list task numbers and have imperative task descriptions.
Also cleaned up an issue with global variable definition order in the Rakefile and made a couple of
quest content fixes.

Spec format

---

Quest_Guide/index.md
Quest_Guide/quests/conditional_statements.md
Quest_Guide/quests/manifests_and_classes.md
Quest_Guide/quests/modules.md
Quest_Guide/quests/ntp.md
Quest_Guide/quests/power_of_puppet.md
Quest_Guide/quests/resource_ordering.md
Quest_Guide/quests/resources.md
Quest_Guide/quests/variables_and_parameters.md
quest_tool/.testing/spec/localhost/variables_and_parameters_spec.rb

Content revisions from first review of Learning VM updates

First revision

---

Quest_Guide/css/main.css
Quest_Guide/index.md
Quest_Guide/quests/power_of_puppet.md

Remove some asides, adjust image padding.

General revisions

---

Quest_Guide/quests/power_of_puppet.md

Signed-off-by: GabrielNicolasAvellaneda <avellaneda.gabriel@gmail.com>

Fixed typo

---

Quest_Guide/quests/conditional_statements.md
Quest_Guide/quests/manifests_and_classes.md
Quest_Guide/quests/modules.md
Quest_Guide/quests/mysql.md
Quest_Guide/quests/ntp.md
Quest_Guide/quests/power_of_puppet.md
Quest_Guide/quests/resource_ordering.md
Quest_Guide/quests/variables_and_parameters.md

Update Quest Guide paths to match changes in 2015.2

Update Quest Guide paths

---

quest_tool/.testing/spec/spec_helper.rb
quest_tool/.testing/test.rb

This reverts commit 76131148f286954c2a1d19cd28d56665815cd56a.

Revert "make rspec 3.3.0 work"

---

Quest_Guide/quests/mysql.md

Added quotes to allow the tree command to properly handle the path glob.

Fixed typo in mysql quest

---

Quest_Guide/quests/resource_ordering.md
Quest_Guide/quests/resources.md

Addressing typos in the learning VM.

Typo fixes

---

Quest_Guide/quests/power_of_puppet.md

Hi
This is a follow up to the email report, with a suggested fix.
Regards
Nathan

Fixing MD typo for gr\_django\_ver.

---

Quest_Guide/quests/modules.md
Quest_Guide/quests/mysql.md

I spotted a minor grammatical error with a missing "of".
Regards
Nathan

Fixing grammatical typo.

---

Quest_Guide/quests/conditional_statements.md
Quest_Guide/quests/mysql.md
Quest_Guide/quests/resource_ordering.md
Quest_Guide/quests/variables_and_parameters.md

These additions might help a little. They did me.
Nathan

Adding clarifications for task 4.

---

Quest_Guide/quests/resources.md

(LEARNVM-208) Copy edits for resources quest

---

quest_tool/.testing/spec/localhost/welcome_spec.rb

(LEARNVM-159) Make welcome quest task specs more permissive

---

Quest_Guide/index.md

Update pupper version output example in the welcome quest

---

quest_tool/.testing/spec/localhost/conditional_statements_spec.rb
quest_tool/.testing/spec/localhost/manifests_and_classes_spec.rb
quest_tool/.testing/spec/localhost/modules_spec.rb
quest_tool/.testing/spec/localhost/resource_ordering_spec.rb
quest_tool/.testing/spec/localhost/variables_and_parameters_spec.rb

change tests to examples in spec tests

---

Quest_Guide/quests/conditional_statements.md

Reference correct fact in review section

---

Quest_Guide/index.md
Quest_Guide/quests/agent_setup.md
Quest_Guide/quests/conditional_statements.md
Quest_Guide/quests/defined_resource_types.md
Quest_Guide/quests/ntp.md
Quest_Guide/quests/power_of_puppet.md
Quest_Guide/quests/resource_ordering.md
Quest_Guide/quests/resources.md
Quest_Guide/quests/variables_and_parameters.md

https://tickets.puppetlabs.com/browse/LEARNVM-277

Copy editing

---

quest_tool/.testing/spec/localhost/agent_setup_spec.rb

The directory created by following the instructions described in the Task 3 is now /opt/puppetlabs/server/data/packages/public/2015.3.2/ubuntu-14.04-amd64.

Fixes Task 3 of the Agent Setup Quest
